services:
  db:
    image: postgres:16
    container_name: nexus-db
    restart: always
    environment:
      POSTGRES_USER: nexus
      POSTGRES_PASSWORD: nexus123
      POSTGRES_DB: nexusdb
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: nexus-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://nexus:nexus123@db:5432/nexusdb
    depends_on:
      - db
    # volumes:
    #   - ./backend:/app
    #   - /app/node_modules

  frontend:
    build: ./frontend
    container_name: nexus-frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules

volumes:
  pgdata: